image: node:14.15.0

before_script:
  - yarn install --cache-folder .yarn
  - rm -rf node_modules/@grafana/data/node_modules

test:
  stage: test
  cache:
    paths:
    - node_modules/
    - .yarn
  script:
    - yarn dev 
